import { Metadata } from "next";
import "animate.css";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/Navbar";
import Footer from "@/components/Footer/Footer";
import ChatBot from "@/components/ChatBot/ChatBot";

// Importing fonts with subsets and variable names for CSS
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Defining metadata for the page
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Root layout for wrapping the app with global layout components
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Navbar />
        <main>{children}</main>
       <ChatBot />
        <Footer />
        </body>
        </html>
    );
}
